services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  WapplerSystems\MessengerDemo\:
    resource: '../Classes/*'

  # Command als Symfony Console Command
  WapplerSystems\MessengerDemo\Command\DispatchDemoEnvelopesCommand:
    public: true
    tags:
      - name: 'console.command'

  # MessageHandler für Messenger
  WapplerSystems\MessengerDemo\MessageHandler\DemoJobMessageHandler:
    tags:
      - name: 'messenger.message_handler'

  messenger.transport.messenger-demo:
    factory: [ '@TYPO3\CMS\Core\Messenger\DoctrineTransportFactory', 'createTransport' ]
    class: 'Symfony\Component\Messenger\Bridge\Doctrine\Transport\DoctrineTransport'
    arguments:
      $options:
        queue_name: 'messenger-demo'
    tags:
      - name: 'messenger.sender'
        identifier: 'messenger-demo'
      - name: 'messenger.receiver'
        identifier: 'messenger-demo'
